version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/services/
    working_dir: /services
    environment:
      DATABASE_ENDPOINT: 'host=services-psql user=postgres password=postgres dbname=services port=5432 sslmode=verify-full'
    ports:
      - 9090:9090
    expose:
      - 9090 

 