version: '3'
services:
  services-psql:
    image: postgres:14.2-alpine
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  
    container_name: services-psql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=services_packages
volumes:
  mysqldata:
    driver: local